name: Azure Storage Account Deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure-Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Output Directory
        run: mkdir -p ${{ github.workspace }}/src/bicep/jsonFilesForScan

      - name: Lint Bicep
        working-directory: '${{ github.workspace }}/src/bicep'
        run: |
          az bicep build --file ./azure_resource.bicep --outdir ./jsonFilesForScan
          ls ./jsonFilesForScan

      - name: Validate Template
        working-directory: '${{ github.workspace }}/src/bicep'
        run: |
          az deployment group validate --name mydeployment1 --resource-group 2158167ResGrp --template-file ./azure_resource.bicep --parameters ./parameter.json
  
      - name: Preview Deployment
        working-directory: '${{ github.workspace }}/src/bicep'
        run: |
          az deployment group what-if --name mydeployment1 --resource-group 2158167ResGrp --template-file ./azure_resource.bicep --parameters ./parameter.json

      - name: Deploy Resource
        working-directory: '${{ github.workspace }}/src/bicep'
        run: |
          az deployment group create --resource-group 2158167ResGrp --template-file ./azure_resource.bicep --parameters ./parameter.json
