name: Deploy Bicep files

on:
  workflow_run:
    workflows: []
    types:
      - manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runBicepLinter: [true, false]
        runTemplateValidation: [true, false]
        runWhatIfTests: [true, false]
        runDeployment: [true, false]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Bicep Linter
        if: ${{ matrix.runBicepLinter == 'true' }}
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az bicep build --file ./azure_resource.bicep --parameters ./parameter.json --outdir ${{ env.TEMPLATE_FILE_DIRECTORY }}/jsonFilesForScan
          ls ${{ env.TEMPLATE_FILE_DIRECTORY }}/jsonFilesForScan

      - name: Run Template Validation
        if: ${{ matrix.runTemplateValidation == 'true' }}
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az deployment sub validate --name mydeployment1 --location canada_central --template-file ./azure_resource.bicep --parameters ./parameter.json

      - name: Run What-If Tests
        if: ${{ matrix.runWhatIfTests == 'true' }}
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az deployment sub what-if --name mydeployment1 --location canadacentral --template-file ./azure_resource.bicep --parameters ./parameter.json

      - name: Deploy Resource
        if: ${{ matrix.runDeployment == 'true' }}
        working-directory: '${{github.workspace}}/src/bicep'
        run: |
          az deployment create --location canadacentral --template-file ./azure_resource.bicep --parameters ./parameter.json
